name: "@smakss/react-scroll-direction"

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm generate
      - uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: |
            ./dist
            package.json

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: built-package
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          scope: "@smakss"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm generate
      - run: |
          if grep -q "beta" package.json; then
            echo "Publishing Beta to npm"
            npm publish --tag beta
          else
            echo "Publishing Release to npm"
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: built-package
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@smakss"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm generate
      - run: |
          if grep -q "beta" package.json; then
            echo "Publishing Beta to GitHub Package Registry"
            npm publish --tag beta
          else
            echo "Publishing Release to GitHub Package Registry"
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
